import { createContext, useContext, useState } from 'react'

const LangContext = createContext(null)

export const translations = {
  es: {
    // Navbar
    navHow: 'Cómo funciona', navSpecs: 'Especialidades',
    navLawyers: 'Abogados', navPricing: 'Precios',
    navLogin: 'Iniciar sesión', navRegister: 'Registrarse',
    navPanel: 'Mi panel', navSignOut: 'Salir',
    // Hero
    heroBadge: 'Justicia digital sin fronteras',
    heroTitle: 'Tu abogado en México,', heroTitleEm: 'donde sea que estés.',
    heroDesc: 'Conectamos a mexicanos en EE.UU. con abogados certificados en México. Videollamadas seguras, pagos en línea y gestión de casos 100% remota.',
    heroCta1: 'Agenda tu consulta express', heroCta2: 'Cómo funciona',
    stat1: 'Abogados certificados', stat2: 'Estados de México', stat3: 'USD por consulta',
    // How it works
    howTitle: '¿Cómo funciona?',
    howDesc: 'Acceso inmediato a asesoría legal en México desde cualquier parte del mundo.',
    step1t: 'Agenda tu consulta', step1d: 'Selecciona fecha y hora. Nuestra plataforma te conecta directamente con un especialista disponible.',
    step2t: 'Paga de forma segura', step2d: 'Paga $49.99 USD con tarjeta o PayPal vía Stripe. Confirmación inmediata por correo.',
    step3t: 'Videollamada de asesoría', step3d: 'Conéctate desde tu navegador sin descargas. Un abogado certificado te asesora en vivo.',
    step4t: 'Cita con especialista', step4d: 'Si tu caso requiere representación, agendas y pagas dentro de la plataforma.',
    // Specialties
    specsTitle: 'Especialidades',
    specsDesc: 'Las áreas legales más demandadas por la comunidad mexicana en EE.UU.',
    // Experience
    expTitle: 'Justicia accesible desde cualquier lugar',
    expDesc1: 'Sabemos que vivir lejos de México no significa dejar de resolver tus asuntos legales.',
    expDesc2: 'Nuestros abogados trabajan en línea con horarios flexibles para la comunidad mexicana en EE.UU.',
    expCard: 'Consulta desde tu teléfono o computadora',
    expCardDesc: 'Sin viajar, sin filas, sin burocracia. Tu abogado certificado te atiende por video.',
    // Pricing
    priceTitle: 'Precio único y transparente',
    priceDesc: 'Sin costos ocultos. Sin sorpresas. Paga solo cuando necesites.',
    priceBadge: 'Consulta por videollamada',
    priceBtn: 'Agenda tu consulta express',
    priceFeat1: 'Videollamada HD segura y privada',
    priceFeat2: 'Abogado certificado con cédula SEP verificada',
    priceFeat3: 'Expediente digital del caso',
    priceFeat4: 'Grabación de sesión disponible',
    priceFeat5: 'Pago en USD o MXN — tarjeta o PayPal',
    priceFeat6: 'Cancelación gratuita hasta 2h antes',
    // Lawyers panel
    lawyersTitle: 'Panel de Abogados',
    lawyersDesc: 'Gestiona tus casos, consultas y clientes desde un solo lugar.',
    // Footer
    footDesc: 'Conectamos a mexicanos en EE.UU. con abogados certificados en México.',
    footPlatform: 'Plataforma', footLegal: 'Legal', footContact: 'Contacto',
    footRights: '© 2025 AbogaMéxico. Todos los derechos reservados.',
    footDisclaimer: 'Los abogados son profesionales independientes certificados.',
    // Auth modals
    loginTitle: 'Iniciar sesión', loginDesc: 'Accede a tu cuenta de AbogaMéxico',
    asClient: 'Soy Cliente', asLawyer: 'Soy Abogado',
    email: 'Correo electrónico', password: 'Contraseña',
    forgotPass: '¿Olvidaste tu contraseña?',
    noAccount: '¿No tienes cuenta?', registerFree: 'Regístrate gratis',
    enterBtn: 'Entrar', enterPanel: 'Entrar al panel',
    registerTitle: 'Crear cuenta', registerDesc: '¿Cómo quieres registrarte?',
    clientTitle: 'Crear cuenta de Cliente', lawyerTitle: 'Registro de Abogado',
    firstName: 'Nombre', lastName: 'Apellido', phone: 'Teléfono',
    country: 'País de residencia', city: 'Ciudad',
    minPass: 'Contraseña (mín. 8 caracteres)',
    createBtn: 'Crear cuenta gratis', requestBtn: 'Solicitar ingreso a la red',
    cedula: 'Cédula Profesional (SEP) *', cedValid: '✓ Formato válido',
    cedError: 'La cédula debe tener entre 6 y 8 dígitos',
    stateDrop: 'Estado donde ejerce', specialty: 'Especialidad principal',
    bio: 'Descripción profesional', bioPlaceholder: 'Tu experiencia y enfoque...',
    alreadyAccount: '¿Ya tienes cuenta?', loginLink: 'Inicia sesión',
    terms: 'Al registrarte aceptas los', termsLink: 'Términos de uso',
    cedulaNote: 'Tu cédula será verificada con la SEP antes de publicar tu perfil.',
    // Dashboard
    welcome: 'Bienvenido', welcomeSub: 'Gestiona tus consultas y casos legales.',
    newConsult: '+ Nueva consulta',
    activeCases: 'Casos activos', closedCases: 'Casos cerrados',
    totalConsults: 'Consultas', totalPaid: 'Total pagado',
    quickActions: '⚡ Acciones rápidas',
    bookConsult: 'Agendar consulta', bookSub: 'Videollamada $49.99 USD',
    myCases: 'Mis casos', myCasesSub: 'Ver expedientes',
    myAppts: 'Mis citas', myApptsSub: 'Acceder a videollamadas',
    myPayments: 'Mis pagos', myPaymentsSub: 'Historial de transacciones',
    upcomingAppts: 'Próximas citas',
    noUpcoming: 'No tienes citas próximas.',
    bookFirst: 'Agendar consulta',
    // Agendar
    agendarTitle: 'Agendar consulta express',
    agendarDesc: 'Selecciona especialidad, fecha y hora. Costo: $49.99 USD.',
    legalSpec: 'Especialidad legal', date: 'Fecha', time: 'Hora',
    describeMatter: 'Describe tu asunto brevemente',
    payConfirm: 'Pagar y confirmar',
    processing: 'Procesando...',
    consultBooked: '¡Consulta agendada!',
    bookedMsg: 'Tu cita está confirmada para',
    at: 'a las', yourRoom: 'Tu sala de videollamada:',
    joinRoom: '📹 Unirse a la sala', newBooking: 'Nueva consulta', goHome: 'Ir al inicio',
    // Tables
    specialty2: 'Especialidad', description: 'Descripción',
    status: 'Estado', result: 'Resultado', dateCol: 'Fecha', timeCol: 'Hora',
    room: 'Sala', amount: 'Monto', stripeId: 'Stripe ID',
    concept: 'Concepto', open: 'Abierto', closed: 'Cerrado',
    paid: 'Pagado', pending: 'Pendiente', upcoming: 'Próxima', completed: 'Completada',
    join: '📹 Unirse', noCases: 'No hay casos en esta categoría.',
    noPayments: 'No hay pagos registrados.',
    totalPaidLabel: 'Total pagado',
    // Profile
    saveChanges: 'Guardar cambios', profileUpdated: '✓ Perfil actualizado',
    profileError: 'Error al guardar: ',
    // Lawyer dashboard
    assignedCases: 'Casos asignados', mySchedule: 'Mi agenda',
    myEarnings: 'Mis ingresos', closeCase: 'Cerrar caso',
    markPaid: 'Marcar como pagado', addResult: 'Agregar resultado',
    resultPlaceholder: 'Describe el resultado del caso...',
    saveResult: 'Guardar resultado',
    noAssigned: 'No tienes casos asignados actualmente.',
    earnings: 'Ingresos totales',
    consultations: 'Consultas realizadas',
    pending2: 'Pagos pendientes',
    nextAppt: 'Próxima cita',
  },
  en: {
    navHow: 'How it works', navSpecs: 'Specialties',
    navLawyers: 'Lawyers', navPricing: 'Pricing',
    navLogin: 'Sign in', navRegister: 'Sign up',
    navPanel: 'My panel', navSignOut: 'Sign out',
    heroBadge: 'Digital justice without borders',
    heroTitle: 'Your lawyer in Mexico,', heroTitleEm: 'wherever you are.',
    heroDesc: 'We connect Mexicans in the U.S. with certified lawyers in Mexico. Secure video calls, online payments and 100% remote case management.',
    heroCta1: 'Book your express consultation', heroCta2: 'How it works',
    stat1: 'Certified lawyers', stat2: 'Mexican states', stat3: 'USD per consultation',
    howTitle: 'How does it work?',
    howDesc: 'Immediate access to legal advice in Mexico from anywhere in the world.',
    step1t: 'Book your consultation', step1d: 'Select a date and time. Our platform connects you directly with an available specialist.',
    step2t: 'Pay securely', step2d: 'Pay $49.99 USD by card or PayPal via Stripe. Immediate email confirmation.',
    step3t: 'Live video consultation', step3d: 'Connect from your browser, no downloads. A certified lawyer advises you live.',
    step4t: 'Appointment with specialist', step4d: 'If your case needs representation, book and pay within the platform.',
    specsTitle: 'Practice Areas',
    specsDesc: 'The most in-demand legal areas for the Mexican community in the U.S.',
    expTitle: 'Justice accessible from anywhere',
    expDesc1: 'Living far from Mexico does not mean you cannot resolve your legal matters.',
    expDesc2: 'Our lawyers work online with flexible hours designed for the Mexican community in the U.S.',
    expCard: 'Consult from your phone or computer',
    expCardDesc: 'No travel, no lines, no bureaucracy. Your certified lawyer attends you by video.',
    priceTitle: 'Simple, transparent pricing',
    priceDesc: 'No hidden fees. No surprises. Pay only when you need it.',
    priceBadge: 'Video call consultation',
    priceBtn: 'Book your express consultation',
    priceFeat1: 'Secure private HD video call',
    priceFeat2: 'Certified lawyer with verified SEP license',
    priceFeat3: 'Digital case file',
    priceFeat4: 'Session recording available',
    priceFeat5: 'Payment in USD or MXN — card or PayPal',
    priceFeat6: 'Free cancellation up to 2h before',
    lawyersTitle: 'Lawyers Panel',
    lawyersDesc: 'Manage your cases, consultations and clients from one place.',
    footDesc: 'We connect Mexicans in the U.S. with certified lawyers in Mexico.',
    footPlatform: 'Platform', footLegal: 'Legal', footContact: 'Contact',
    footRights: '© 2025 AbogaMéxico. All rights reserved.',
    footDisclaimer: 'Lawyers are independent certified professionals.',
    loginTitle: 'Sign in', loginDesc: 'Access your AbogaMéxico account',
    asClient: 'I am a Client', asLawyer: 'I am a Lawyer',
    email: 'Email address', password: 'Password',
    forgotPass: 'Forgot your password?',
    noAccount: "Don't have an account?", registerFree: 'Sign up free',
    enterBtn: 'Sign in', enterPanel: 'Enter panel',
    registerTitle: 'Create account', registerDesc: 'How do you want to register?',
    clientTitle: 'Create Client Account', lawyerTitle: 'Lawyer Registration',
    firstName: 'First name', lastName: 'Last name', phone: 'Phone',
    country: 'Country of residence', city: 'City',
    minPass: 'Password (min. 8 characters)',
    createBtn: 'Create free account', requestBtn: 'Request to join the network',
    cedula: 'Professional License (SEP) *', cedValid: '✓ Valid format',
    cedError: 'License must be between 6 and 8 digits',
    stateDrop: 'State where you practice', specialty: 'Main specialty',
    bio: 'Professional description', bioPlaceholder: 'Your experience and approach...',
    alreadyAccount: 'Already have an account?', loginLink: 'Sign in',
    terms: 'By registering you accept the', termsLink: 'Terms of use',
    cedulaNote: 'Your license will be verified with SEP before publishing your profile.',
    welcome: 'Welcome', welcomeSub: 'Manage your legal consultations and cases.',
    newConsult: '+ New consultation',
    activeCases: 'Active cases', closedCases: 'Closed cases',
    totalConsults: 'Consultations', totalPaid: 'Total paid',
    quickActions: '⚡ Quick actions',
    bookConsult: 'Book consultation', bookSub: 'Video call $49.99 USD',
    myCases: 'My cases', myCasesSub: 'View files',
    myAppts: 'My appointments', myApptsSub: 'Access video calls',
    myPayments: 'My payments', myPaymentsSub: 'Transaction history',
    upcomingAppts: 'Upcoming appointments',
    noUpcoming: 'You have no upcoming appointments.',
    bookFirst: 'Book consultation',
    agendarTitle: 'Book express consultation',
    agendarDesc: 'Select specialty, date and time. Cost: $49.99 USD.',
    legalSpec: 'Legal specialty', date: 'Date', time: 'Time',
    describeMatter: 'Briefly describe your matter',
    payConfirm: 'Pay and confirm',
    processing: 'Processing...',
    consultBooked: 'Consultation booked!',
    bookedMsg: 'Your appointment is confirmed for',
    at: 'at', yourRoom: 'Your video call room:',
    joinRoom: '📹 Join room', newBooking: 'New consultation', goHome: 'Go home',
    specialty2: 'Specialty', description: 'Description',
    status: 'Status', result: 'Result', dateCol: 'Date', timeCol: 'Time',
    room: 'Room', amount: 'Amount', stripeId: 'Stripe ID',
    concept: 'Concept', open: 'Open', closed: 'Closed',
    paid: 'Paid', pending: 'Pending', upcoming: 'Upcoming', completed: 'Completed',
    join: '📹 Join', noCases: 'No cases in this category.',
    noPayments: 'No payments registered.',
    totalPaidLabel: 'Total paid',
    saveChanges: 'Save changes', profileUpdated: '✓ Profile updated',
    profileError: 'Error saving: ',
    assignedCases: 'Assigned cases', mySchedule: 'My schedule',
    myEarnings: 'My earnings', closeCase: 'Close case',
    markPaid: 'Mark as paid', addResult: 'Add result',
    resultPlaceholder: 'Describe the outcome of the case...',
    saveResult: 'Save result',
    noAssigned: 'You have no assigned cases currently.',
    earnings: 'Total earnings',
    consultations: 'Consultations done',
    pending2: 'Pending payments',
    nextAppt: 'Next appointment',
  }
}

export function LangProvider({ children }) {
  const [lang, setLang] = useState('es')
  const t = translations[lang]
  const toggleLang = () => setLang(l => l === 'es' ? 'en' : 'es')
  return (
    <LangContext.Provider value={{ lang, t, toggleLang }}>
      {children}
    </LangContext.Provider>
  )
}

export const useLang = () => useContext(LangContext)
